// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://judervhdilvmgqjoxpfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1ZGVydmhkaWx2bWdxam94cGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MzUwMTIsImV4cCI6MjA2MzExMTAxMn0.2Ok57zbQTQlstbWl3nQG-hlNHsSlFTHaoBYxQjkjoys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);